services:
  - type: web
    name: binance-testnet-webhook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --preload --bind 0.0.0.0:$PORT"
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: BINANCE_UMF_BASE
        value: https://testnet.binancefuture.com
